server:
  port: 8080

app:
  version: 1.0.0
  name: Smart Expense Tracker
  db:
    source:
      jdbcUrl: jdbc:sqlite:./db/source/phone.db
      driverClassName: org.sqlite.JDBC
      metadata:
        path: "./db/source/phone.db"
        name: "phone.db"
      hikari:
        maximumPoolSize: 1

    persist:
      jdbcUrl: jdbc:sqlite:./db/persist/persist.db
      driverClassName: org.sqlite.JDBC
      metadata:
        schema: persistDBSchema.sql
        path: ./db/persist/persist.db
        name: persist.db
      hikari:
        maximumPoolSize: 1

  path:
    sourceDbPath: C:\Users\syedi\AppData\Local\Packages\Microsoft.YourPhone_8wekyb3d8bbwe\LocalCache\Indexed\fe43b75f-00e7-4bb9-b9c5-077218994971\System\Database
    targetDbPath: C:\Users\syedi\Desktop\Projects\smart-fin-tracker\backend\db\source


logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){dim} %clr(%-5level) %clr([%thread]){magenta} %clr(%logger{0}){cyan} - %clr(%msg){yellow}%n"
  level:
    root: INFO
    org.springframework.data.jdbc: DEBUG

#  file:
#    name: logs/backend-app.log
#( also define policy : file size, how long history stored)

